#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-antlr
Version  : 2.7.2
Release  : 2
URL      : https://repo1.maven.org/maven2/antlr/antlr/2.7.2/antlr-2.7.2.jar
Source0  : https://repo1.maven.org/maven2/antlr/antlr/2.7.2/antlr-2.7.2.jar
Source1  : https://repo1.maven.org/maven2/antlr/antlr/2.7.2/antlr-2.7.2.pom
Source2  : https://repo1.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.jar
Source3  : https://repo1.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : ANTLR-PD BSD-3-Clause
Requires: mvn-antlr-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-antlr package.
Group: Data

%description data
data components for the mvn-antlr package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/antlr/antlr/2.7.2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/antlr/antlr/2.7.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/antlr/antlr/2.7.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/antlr/antlr/2.7.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/antlr/antlr/2.7.7
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/antlr/antlr/2.7.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/antlr/antlr/2.7.7
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/antlr/antlr/2.7.7


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/antlr/antlr/2.7.2/antlr-2.7.2.jar
/usr/share/java/.m2/repository/antlr/antlr/2.7.2/antlr-2.7.2.pom
/usr/share/java/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar
/usr/share/java/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.pom
